CREATE TABLE  "PRICE_DATA" 
   (	"DATA_DATE" DATE, 
	"OPEN" NUMBER, 
	"HIGH" NUMBER, 
	"LOW" NUMBER, 
	"CLOSE" NUMBER, 
	"ADJ_CLOSE" NUMBER, 
	"VOLUME" NUMBER, 
	"TICKER" VARCHAR2(50)
   )
/

  CREATE UNIQUE INDEX  "PRICE_DATA_PK" ON  "PRICE_DATA" ("TICKER", "DATA_DATE")
/

ALTER TABLE  "PRICE_DATA" ADD CONSTRAINT "PRICE_DATA_PK" PRIMARY KEY ("TICKER", "DATA_DATE")
  USING INDEX  "PRICE_DATA_PK"  ENABLE
/
