DROP TABLE pt_paper;
/****
-- GTT
CREATE GLOBAL TEMPORARY TABLE PT_PAPER
("PT_ID" NUMBER(20,0), 
	"SEQ_NO" NUMBER(20,0), 
	"L_IDX_AVG" NUMBER(15,10), 
	"L_IDX_STDEV" NUMBER(15,10), 
	"Z_SCORE" NUMBER(15,10), 
	"SIGNAL" VARCHAR2(1), 
	"STS" VARCHAR2(30 BYTE), 
	"PROFIT_LOSS" NUMBER(20,2), 
	"PROFIT_LOSS_ACC" NUMBER(20,2), 
	"TX_PRICE_A" NUMBER(20,2), 
	"TX_VOL_A" NUMBER(20,0), 
	"TX_AMT_A" NUMBER(20,2), 
	"TX_PRICE_B" NUMBER(20,2), 
	"TX_VOL_B" NUMBER(20,0), 
	"TX_AMT_B" NUMBER(20,2), 
	"MTM" NUMBER(20,2),
  CONSTRAINT pt_paper_pk PRIMARY KEY (pt_id, seq_no)
)
ON COMMIT PRESERVE ROWS;
****/
-- Standard
CREATE TABLE "LISO"."PT_PAPER" 
   ("PT_ID" NUMBER(20,0), 
	"SEQ_NO" NUMBER(20,0), 
	"L_IDX_AVG" NUMBER(15,10), 
	"L_IDX_STDEV" NUMBER(15,10), 
	"Z_SCORE" NUMBER(15,10), 
	"SIGNAL" VARCHAR2(1), 
	"STS" VARCHAR2(30 BYTE), 
	"PROFIT_LOSS" NUMBER(20,2), 
	"PROFIT_LOSS_ACC" NUMBER(20,2), 
	"TX_PRICE_A" NUMBER(20,2), 
	"TX_VOL_A" NUMBER(20,0), 
	"TX_AMT_A" NUMBER(20,2), 
	"TX_PRICE_B" NUMBER(20,2), 
	"TX_VOL_B" NUMBER(20,0), 
	"TX_AMT_B" NUMBER(20,2), 
	"MTM" NUMBER(20,2), 
	 CONSTRAINT "PT_PAPER_PK" PRIMARY KEY ("PT_ID", "SEQ_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 2097152 NEXT 2097152 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 2097152 NEXT 2097152 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

