DECLARE
   l_rc SMALLINT;
BEGIN
   l_rc := pa_zfcc_07.import_aqh( 'AAPL.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'AMD.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'AMLP.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'AMT.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'AMZN.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'ARKF.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'ARKG.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'ARKK.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'ARKQ.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'ARKX.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'ASML.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'AWAY.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'BAC.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'BAL.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'BATT.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'BCD.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'BRK-B.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'CANE.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'CIBR.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'CLOU.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'CNRG.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'COMT.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'COPX.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'CORN.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'CPER.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'CVX.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'CWH.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'DBB.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'DIA.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'EFA.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'EWA.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'EWC.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'EWZ.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'F.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'FCG.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'FTGC.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'GLD.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'GOOGL.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'GRID.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'HD.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'HERO.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'HYG.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'IAI.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'IBB.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'ICLN.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'IEO.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'IFRA.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'IHI.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'INDA.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'ITB.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'ITEQ.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'IYF.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'IYT.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'JETS.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'JNJ.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'JNK.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'JO.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'JPM.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'KRE.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'LCII.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'LIT.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'MA.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'META.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'MJ.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'MSFT.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'NANR.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'NVDA.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'O.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'PALL.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'PBW.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'PG.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'PLTM.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'QCLN.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'REMX.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'SCHH.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'SLV.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'SLX.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'SMH.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'SMOG.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'SOYB.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'SPCX.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'SPY.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'TAN.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'THO.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'TSLA.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'TSM.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'UNG.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'UNH.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'USO.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'V.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'VBK.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'VBR.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'VDE.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'VHT.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'VNM.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'VOE.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'VOT.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'VT.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'VTV.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'VUG.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'WEAT.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'WFC.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'WGO.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'WMT.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'WPC.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'XBI.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'XES.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'XLB.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'XLC.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'XLI.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'XLK.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'XLP.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'XLRE.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'XLU.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'XLY.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'XME.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'XOM.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'XPH.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'XRT.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
   l_rc := pa_zfcc_07.import_aqh( 'XTN.aqh');
   DBMS_OUTPUT.PUT_LINE(l_rc);
END;
/
