CREATE MATERIALIZED VIEW MV_LATEST_PRICE_DT 
BUILD IMMEDIATE
REFRESH ON COMMIT 
FORCE 
ENABLE  QUERY REWRITE
AS 
SELECT MAX(data_date) latest_price_dt
FROM price_data
WHERE bar_size = 'EOD';

CREATE MATERIALIZED VIEW MV_CORR_RPT 
BUILD DEFERRED
REFRESH ON DEMAND 
COMPLETE 
DISABLE  QUERY REWRITE
AS
SELECT * FROM V_CORR_RPT;
